### ISSUE TITLE
Missing formfields TYPE parameterr

### ISSUE THREAD

**Issue by alexmac05** [hellosign/hellosign-java-sdk#102]
Please add this parameter (form_fields_per_document TYPE) to the class FormField. 

An example to see this in use would be using this endpoint

https://app.hellosign.com/api/reference#create_embedded_unclaimed_draft
and using the parameter form_fields_per_document TYPE. 

In the Java SDK. 

Need this for end to end testing. 

It should be added here....
package com.hellosign.sdk.resource.support.types;
public enum FieldType {
    text,
    signature,
    initials,
    checkbox,
    date_signed;
    private FieldType() {
    }
}

**Comment by robbiediaz** [comment]
I need this functionality in an app I'm building as well. Is there any way we can get the pull request merged in @jspaetzel? I saw it was a WIP branch, but what's left to be done on it?

**Comment by jspaetzel** [comment]
@robbiediaz just need to write a test. I'll make some time and finish this up this week, maybe today.

**Comment by robbiediaz** [comment]
Awesome, that sounds great! Thanks for getting back to me :)

**Comment by jspaetzel** [comment]
New release with this added. Should show up on maven shortly.
https://github.com/hellosign/hellosign-java-sdk/releases/tag/4.2.2

**Comment by robbiediaz** [comment]
Thanks @jspaetzel! :D
