### ISSUE TITLE
Java 8 support on version 5.1.0+

### ISSUE THREAD

**Issue by fabsanchez** [hellosign/hellosign-java-sdk#121]
Hello,

I'm developing a Java desktop application that is compiled and run with java 8 (update 1.8.0_202).

I've tried to use the latest version (5.1.0) of hellosign-java-sdk but I get the following error:

```
C:\projects\pst-hellosign\src\main\java\uk\fab\sign\MyHelloSign.java:3: error: cannot access HelloSignClient
import com.hellosign.sdk.HelloSignClient;
                        ^
  bad class file: C:\Users\fabri\.gradle\caches\modules-2\files-2.1\com.hellosign\hellosign-java-sdk\5.1.0\1ba3583d2cc779f35473dca51bc45c517042dedb\hellosign-java-sdk-5.1.0.jar(com/hellosign/sdk/HelloSignClient.class)
    class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
```
This error is not present if I use version 4.2.2 which, I know from the commit comments, is before java 11 support was added.

Is there a way to use java 8 with the latest versions of hellosign-java-sdk?

Will recompiling the source code under java 8 work?

Best regards,
Fab

**Comment by fabsanchez** [comment]
In case someone else needs to use java 8 with this version of hellosign-java-sdk, it's a very simple process to convert the source code:
I downloaded the source code and modified code calls not supported by java 8, these were:
- String method isBlank(). E.g. change **_prefix.is Blank()_** to **_prefix.trim().length() == 0_**, *_!prefix.is Blank()_** to **_prefix.trim().length() > 0_**
- Removing 'var' and setting it to the variable type being used. E.g. change **_var role = entry.getKey()_** to **_String role = entry.getKey();_** you'll need to check the code for the expected type.

After correcting these changes, not more than 5 or 6 of them in total, the gradle task: other > fatJar can be used to create the full hellosign-java-sdk-5.1.0.jar for use with java 8.

**Comment by hazemhamedhs** [comment]
Thank you for sharing the workaround, Fab. 

Will make sure to call it our with future clients.
