### ISSUE TITLE
User Agent incorrectly set by Client

### ISSUE THREAD

**Issue by codylerum** [hellosign/hellosign-java-sdk#156]
When looking at requests created by the java client in Hello Sign the `User Agent` is not properly resolved and shows like `hellosign-java-sdk/${project.version}`

![image](https://user-images.githubusercontent.com/217262/146833649-6b375823-62cf-4443-b43c-181c581af4e9.png)

**Comment by codylerum** [comment]
Looks like when this was created the maven build filtered over the /src/main/resources directory

https://github.com/hellosign/hellosign-java-sdk/blob/4a72ae2d3566d612ef3e6a1d21009b28aca2c242/pom.xml#L57

This must not have been carried over when the build was converted to gradle

**Comment by codylerum** [comment]
@jspaetzel I'm not a gradle guy so this is probably the extent of what I can do.  I did a PR but I can't tell if the test suite is actually being run by github actions

**Comment by jspaetzel** [comment]
Thanks for the PR @codylerum! Next time I or someone on my team makes changes to this SDK I'll be sure to verify this is working the way we're expecting and merge it in.
