### ISSUE TITLE
Upgrade to Java 8

### ISSUE THREAD

**Issue by cmpaul** [hellosign/hellosign-java-sdk#48]
Java 7 reached EOL in April 2015 and is no longer receiving public updates.

This is the primary reason to move to Java 8, but there are other benefits, including lambda support and `Optional` class support.

**Comment by jspaetzel** [comment]
Oh yeah this already happened at some point. Closing this! Next up... Java 11. https://github.com/hellosign/hellosign-java-sdk/pull/106
