### ISSUE TITLE
Ability to Sending Text Tags with pre-set values

### ISSUE THREAD

**Issue by latoyazamill** [hellosign/hellosign-java-sdk#92]
https://app.hellosign.com/api/textTagsWalkthrough - "Sending Text Tags with pre-set values" Section

Example text tag: [text-merge|req|sender|organization_name|api_id] Usage of custom_fields for the above text tag: custom_fields:[{"name":"organization_name", "value" : "Acme Co."}]

**Comment by jspaetzel** [comment]
This should be resolved with v4.1.0.
