### ISSUE TITLE
Custom Field Support with Embedded Requests

### ISSUE THREAD

**Issue by codylerum** [hellosign/hellosign-java-sdk#96]
https://app.hellosign.com/api/embeddedRequestingWalkthrough

It does not appear possible to set custom fields when creating an Embedded Request 

Embedded Request is missing the EmbeddedRequest#addCustomField and EmbeddedRequest#setCustomFieldValue methods.

**Comment by jspaetzel** [comment]
This'll be resolved in 4.1.0
