### ISSUE TITLE
Thread safety discrepancy between 3.x.x and 4.x.x

### ISSUE THREAD

**Issue by mpiela** [hellosign/hellosign-java-sdk#99]
I don't know if this is a feature or a bug, but the 3.x.x HelloSignClient seems to written in a thead-safe way. I can create a single instance of the client and reuse it from multiple threads.
But the 4.x.x version seems to be lacking this feature - a single instance of HttpClient is created inside of HelloSignClient and it gets modified and reused for all requests. This creates a very serious threat that multiple threads will overwrite each others' changes in the HttpClient and send unexpected requests to the API.

**Comment by hazemhamedhs** [comment]
Hi @mpiela 

This is Hazem from API support.

If this is still an issue, would you mind getting back to us by creating a ticket to apisupport@hellosign.com with what the HelloSign SDK is doing in response when hitting the endpoint in your implementation?

We will be on the look-out for your ticket in our queue.
